name: athernos_server_manger_client
description: Manage your athernos server from your phone or desktop without the need of the athernos website
publish_to: none
version: 0.0.2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.1.3
  dio: ^4.0.6
  flutter_hooks: ^0.18.5+1
  riverpod_annotation: ^1.1.1
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3
  dynamic_color: ^1.6.2
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.17
  intl: ^0.18.0
  animations: ^2.0.7
  logging: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  riverpod_generator: ^1.1.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
